---
title: "01_site_maps"
author: "Alex Macadam"
date: "2023-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(raster)
library(tidyverse)
library(ggspatial)
library(sf)
library(dataaimsr)
library(gisaimsr)
library(ggrepel)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(cowplot)
```

```{r}
gbr_feat<- gbr_feat
```

```{r}
coordinates <- read.csv("/Users/alexmacadam/Documents/GitHub/AGF-Outplanting/data/collection_site_coordinates.csv") |>
  mutate(Reef = factor(Reef, levels=c("Wood","Martin","Arlington","Davies","Fantome Is.")))

sf <-
  coordinates %>% 
    st_as_sf(coords = c("Lon", "Lat"), crs= 4326, remove = F)
```

```{r}
cols = c("#D1CAA1","#D1CAA1","#593C68","#593C68","#593C68")
```

```{r}
esri_topo <- paste0('https://services.arcgisonline.com/arcgis/rest/services/',
                   'World_Topo_Map/MapServer/tile/${z}/${y}/${x}.jpeg')

map2<- ggplot() +
  annotation_map_tile(type = esri_topo, zoom = 8) +
  layer_spatial(data = sf, color = 'black', size = 4) +
  coord_sf(xlim = c(140, 148), ylim = c(-10, -20), expand = F, crs= 4326) +
  annotation_scale() +
  geom_label_repel(data = coordinates, mapping = aes(x = Lon, y = Lat, label = Reef, fill = Reef), hjust = 0, vjust = 0, show.legend = FALSE) +
  #scale_fill_manual(values = cols)+
  #scale_colour_manual(values = cols) +
  labs(x = "Longitude", y = "Latitude")
map2
```

```{r}
# Small Map of Australia
sf_use_s2(FALSE) #We don't want to use a spherical geometry for now

world <- ne_countries(scale = "medium", returnclass = "sf")
AUS <- world %>% 
  filter(name_long == "Australia") 

map_aus <- ggplot(data = AUS) +
  geom_sf(size = 0.1, fill = "#333333") +
  coord_sf(expand = F, xlim = c(112,154), ylim = c(-45,-10)) +
  geom_rect(aes(xmin=142, xmax=153, ymin=-25, ymax=-10),fill="transparent", linetype = "dotted", color="firebrick") +
  theme(plot.background = element_rect(fill = "transparent", colour = NA),
        panel.background = element_rect(fill = "transparent"),
        panel.grid = element_blank(),
        panel.border= element_blank(),
        axis.text.x= element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank())

map_aus
```

```{r}
# first define box
cropbox <- extent(142, 152, -22, -10) %>%
  as("SpatialPolygons") %>%
  st_as_sf %>%
  st_set_crs(st_crs(gbr_feat))
```

```{r}
site_map2<- map2 + annotation_custom(ggplotGrob(map_aus), xmin = 139, xmax = 144, 
                       ymin = -20, ymax = -17)
site_map2
```

######################################
```{r}
coordinates <- read.csv("/Users/alexmacadam/Documents/GitHub/AGF-Outplanting/data/outplant_site_coordinates.csv") |>
  mutate(Reef = factor(Reef, levels=c("North Fantome Is.")))
```

```{r}
cols = c("#593C68")
```

```{r}
# Small Map of Australia
sf_use_s2(FALSE) #We don't want to use a spherical geometry for now

world <- ne_countries(scale = "medium", returnclass = "sf")
AUS <- world %>% 
  filter(name_long == "Australia") 

map_gbr <- ggplot(data = AUS) +
  geom_sf(size = 0.1, fill = "#333333") +
  coord_sf(expand = F, xlim = c(142,153), ylim = c(-20,-10)) +
  geom_rect(aes(xmin=146.4, xmax=146.8, ymin=-18.8, ymax=-18.5),fill="transparent", linetype = "solid", color="firebrick", size = 1) +
  theme(plot.background = element_rect(fill = "transparent", colour = NA),
        panel.background = element_rect(fill = "transparent"),
        panel.grid = element_blank(),
        panel.border= element_blank(),
        axis.text.x= element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank())

map_gbr
```

```{r}
# first define box
cropbox <- extent(146.4, 146.8, -18.9, -18.5) %>%
  as("SpatialPolygons") %>%
  st_as_sf %>%
  st_set_crs(st_crs(gbr_feat))
```

```{r}
esri_topo <- paste0('https://services.arcgisonline.com/arcgis/rest/services/',
                   'World_Imagery/MapServer/tile/${z}/${y}/${x}.jpeg')

palms_map<- ggplot() +
  annotation_map_tile(type = esri_topo, zoom = 11, alpha = 0.8) +
  layer_spatial(data = sf, color = 'white', size = 4) +
  coord_sf(xlim = c(146.45, 146.75), ylim = c(-18.5, -18.85), expand = F, crs= 4326) +
  #fixed_plot_aspect(ratio = 1) +
  labs(x = "Longitude", y = "Latitude") +
  geom_label_repel(data = coordinates, mapping = aes(x = Long, y = Lat, label = Reef, fill = Reef), hjust = 0, vjust = 0, show.legend = FALSE) +
  #geom_point(data = coordinates, mapping = aes(x = Long, y = Lat, fill = Reef), shape = 21, size = 4, show.legend = FALSE) +
  scale_fill_manual(values = cols)+
  scale_colour_manual(values = cols)

palms_map
```

```{r}
esri_topo <- paste0('https://services.arcgisonline.com/arcgis/rest/services/',
                   'World_Topo_Map/MapServer/tile/${z}/${y}/${x}.jpeg')

palms_map<- ggplot() +
  annotation_map_tile(type = esri_topo, zoom = 12, alpha = 0.8) +
  layer_spatial(data = sf, color = 'white', size = 4) +
  coord_sf(xlim = c(146.45, 146.75), ylim = c(-18.5, -18.85), expand = F, crs= 4326) +
  #fixed_plot_aspect(ratio = 1) +
  labs(x = "Longitude", y = "Latitude") +
  geom_label_repel(data = coordinates, mapping = aes(x = Long, y = Lat, label = Reef, fill = Reef), hjust = 0, vjust = 0, show.legend = FALSE) +
      annotation_scale(location = "tr", width_hint = 0.5) +
    annotation_north_arrow(location = "tr", which_north = "true", pad_x = unit(0.25, "in"), pad_y = unit(0.25, "in"), style = north_arrow_fancy_orienteering) +
  #geom_point(data = coordinates, mapping = aes(x = Long, y = Lat, fill = Reef), shape = 21, size = 4, show.legend = FALSE) +
  scale_fill_manual(values = cols)+
  scale_colour_manual(values = cols)

palms_map2<- palms_map + annotation_custom(ggplotGrob(map_gbr), xmin = 146.45, xmax = 146.55, 
                       ymin = -18.85, ymax = -18.75)
palms_map2
```
