---
title: "Chapter 5- Outplanting environment data"
author: "Alex Macadam"
date: '2023-01-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggpubr)
```


Set working diretory
```{r}
setwd("C:/Users/amacadam/Dropbox/PhD/Chapter 5- Outplanting/Chapter 5 Data")
```
Make plot of the environment data that was taken from the HOBO logger attached to the the deployment tables

Load environment data
```{r}
table_1 <- read.csv("C:/Users/amacadam/Dropbox/PhD/Chapter 5- Outplanting/Chapter 5 Data/Outplant_Experiment_EnvData_Table_1.csv", header=T)
table_2 <- read.csv("C:/Users/amacadam/Dropbox/PhD/Chapter 5- Outplanting/Chapter 5 Data/Outplant_Experiment_EnvData_Table_2.csv", header = T)
dhw<- read.csv("C:/Users/amacadam/Dropbox/PhD/Chapter 5- Outplanting/Chapter 5 Data/DHW_data_Fantome.csv", header = T)
```


```{r}
#combine data
env_data <- rbind(table_1, table_2)
```

```{r}
#change date time format table data
env_data$Date_Time2 = as.POSIXct(env_data$Date_Time, format = '%d/%m/%Y %H:%M')
env_data$Date = as.Date(env_data$Date_Time2, format ='%d-%m-%Y')
```

```{r}
#change date time format DHW
dhw$Date_time = as.POSIXct(dhw$time_UTC, format = '%Y-%m-%dT%H:%M:%SZ')
dhw$Date = as.Date(dhw$Date_time, format ='%d-%m-%Y')
```

```{r}
#factorise
env_data <- env_data %>% mutate(Table = factor(Table))
```

```{r}
#add mean SST column
env_data<- env_data %>%
  mutate(Mean_temp = 27.79)
```

```{r}
glimpse(env_data)
glimpse(dhw)
```

```{r}
#summarise temp data
max_daily_temp <- env_data %>%
  group_by(Date) %>%
  summarise(Av_temp = max(Temp_C))
```

```{r}
#summarise lux data
max_daily_lux <- env_data %>%
  filter(Time >='11:14' & Time < '15:14') %>%
  group_by(Date) %>%
  summarise(Av_lux = max(Intensity_Lux))
```

```{r}
#join datasets
temp_lux<- dplyr::left_join(max_daily_temp, max_daily_lux) %>% na.omit()
glimpse(temp_lux)
```

```{r}
#join datasets
temp_lux_dhw<- dplyr::left_join(temp_lux, dhw)
temp_lux_dhw$BAA_MAX <- as.numeric(temp_lux_dhw$BAA_MAX)
glimpse(temp_lux_dhw)
```

```{r}
Temp_plot<- temp_lux_dhw %>% 
  ggplot(aes(x=Date)) +
  geom_line(aes(y=Av_temp), size=1, colour = "firebrick3") +
  scale_y_continuous(limits=c(25,32), breaks=seq(25,32,1)) +
  #scale_color_manual(values=c('goldenrod2', 'firebrick4'), name="", guide=FALSE) +
  labs(x='Date', y="Temperature (°C)") +
  theme_pubr(base_size = 10) +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)))
```

```{r}
DHW_plot<- temp_lux_dhw %>% 
  ggplot(aes(x=Date)) +
  geom_area(aes(y=DHW_Celsius_weeks), size=1, fill = "#F7931E", alpha = 0.4) +
  #scale_color_manual(values=c('goldenrod2', 'firebrick4'), name="", guide=FALSE) +
  scale_y_continuous(position = "right") +
  labs(x='Date', y="Degree heating weeks") +
  theme_pubr(base_size = 10) +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)))
DHW_plot
```

```{r}
DHW_plot<- temp_lux_dhw %>% 
  ggplot(aes(x=Date)) +
  geom_col(aes(y=DHW_Celsius_weeks), size=1, color = "black", fill = "#F7931E", alpha = 0.4) +
  #scale_color_manual(values=c('goldenrod2', 'firebrick4'), name="", guide=FALSE) +
  scale_y_continuous(position = "right") +
  labs(x='Date', y="Degree heating weeks") +
  theme_pubr(base_size = 10) +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)))
DHW_plot
```

```{r}
dual_plot <- function(data, x, y_left, y_right){
  x <- ensym(x)
  y_left <- ensym(y_left)
  y_right <- ensym(y_right)

  min_slope_ratio <- 1
  ratio_model <- lm(eval(y_left) ~ eval(y_right), data = data)
  ratio_slope <- ratio_model$coefficients[[2]]

  if (ratio_model$coefficients[[2]] < min_slope_ratio) {
    ratio_model <- lm(eval(y_left) ~ 1, data = data)
    ratio_slope <- min_slope_ratio
  }
  ratio_intercept <- ratio_model$coefficients[[1]]


  data %>%
    select(!!x, !!y_left, !!y_right) %>%
    mutate(!!y_right := !!y_right * ratio_slope + ratio_intercept) %>%
    # mutate(!!y_right := predict(ratio_model)) %>%
    gather(k, v, -!!x) %>%
    ggplot() +
    geom_line(aes(!!x, v, colour = k), size = 1) +
    scale_y_continuous(sec.axis = sec_axis(~ . / ratio_slope -
                                             ratio_intercept,
                                           name = rlang::as_string(y_right))) +
      theme_pubr(base_size = 10) +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4))) +
    labs(y = rlang::as_string(y_left))
}
```

```{r}
temp_lux_dhw %>% 
  dual_plot(Date, Av_temp, DHW_Celsius_weeks) + labs(x= 'Date', y= "Temperature (°C)", y2= "Lux")
```
```{r}
ggsave('C:/Users/amacadam/Dropbox/PhD/Chapter 5- Outplanting/Chapter 5 Scripts/Chapter-5--Outplanting-AGF-corals/Figures/Temp_plot.pdf', Temp_plot,
       device="pdf", width=10, height=6, units = "in")
ggsave('C:/Users/amacadam/Dropbox/PhD/Chapter 2- Physiology/Chapter 2 figures/First draft figures/Figures/Temp_plot.png', Temp_plot,
       device="png", width=10, height=6, units = "in", dpi = 1000)
```

```{r}
ggsave('C:/Users/amacadam/Dropbox/PhD/Chapter 5- Outplanting/Chapter 5 Scripts/Chapter-5--Outplanting-AGF-corals/Figures/DHW_plot2.pdf', DHW_plot,
       device="pdf", width=10, height=6, units = "in")
ggsave('C:/Users/amacadam/Dropbox/PhD/Chapter 5- Outplanting/Chapter 5 Scripts/Chapter-5--Outplanting-AGF-corals/Figures/DHW_plot.png', DHW_plot,
       device="png", width=10, height=6, units = "in", dpi = 1000)
```